version: '3'

services:
  catalog_api:
    build:
      context: ./catalog
    ports:
      - "5050:5000"

  purchase_api:
    build:
      context: ./purchase
    ports:
      - "5060:5000"

  gateway_api:
    build:
      context: ./gateway
    ports:
      - "8080:5000"
